# Generated by Django 5.1 on 2024-08-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
