# Generated by Django 5.1 on 2024-09-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bistroapp', '0003_alter_chef_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
