# Generated by Django 5.1 on 2024-09-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistroapp', '0006_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(upload_to='chef/'),
        ),
    ]
