# Generated by Django 5.1 on 2024-09-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bistroapp', '0008_rename_image_chef_chefimg_alter_menu_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chef',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
