# Generated by Django 5.1 on 2024-09-11 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistroapp', '0010_chef_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('bistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bistroapp.bistro')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
