# Generated by Django 5.1 on 2024-09-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bistroapp', '0011_bistro_review_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bistro',
        ),
        migrations.DeleteModel(
            name='Bistro',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
